"""
ETH OAuth Python SDK

A library for verifying JWT tokens generated by the ETH OAuth browser extension.
"""

from .blockchain import BlockchainClient, get_public_key
from .crypto import (
                     base64url_decode,
                     base64url_encode,
                     hex_to_bytes,
                     verify_ed25519_signature,
)
from .jwt_verifier import JWTVerificationError, JWTVerifier, parse_jwt, verify_jwt

__version__ = "0.1.0"

__all__ = [
    "JWTVerifier",
    "verify_jwt",
    "parse_jwt",
    "JWTVerificationError",
    "get_public_key",
    "BlockchainClient",
    "verify_ed25519_signature",
    "base64url_decode",
    "base64url_encode",
    "hex_to_bytes",
]

